# Generated by Django 4.2.4 on 2023-08-09 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.CharField(max_length=10, null=True)),
                ('intensity', models.IntegerField(null=True)),
                ('sector', models.CharField(max_length=100, null=True)),
                ('topic', models.CharField(max_length=100, null=True)),
                ('insight', models.TextField(null=True)),
                ('url', models.URLField(null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('start_year', models.CharField(max_length=10, null=True)),
                ('impact', models.CharField(max_length=100, null=True)),
                ('added', models.DateTimeField(auto_now_add=True, null=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('relevance', models.IntegerField(null=True)),
                ('pestle', models.CharField(max_length=100, null=True)),
                ('source', models.CharField(max_length=100, null=True)),
                ('title', models.TextField(null=True)),
                ('likelihood', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
